import Head from "next/head"

import { Navbar, Features, Welcome } from "../components"

export default function Home() {
    return (
        <div>
            {/* <TransactionContext> */}
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <Welcome />
            <Features />
            {/* </TransactionContext> */}
        </div>
    )
}
